(global-set-key (kbd "C-x C-s") 'clean-and-save-buffer)
(global-set-key (kbd "C-' C-b") 'ibuffer)
(global-set-key (kbd "C-' C-f") 'find-file-in-project)
(global-set-key (kbd "C-' C-g") 'magit-status)
(global-set-key (kbd "C-' C-a") 'ack-and-a-half)
(global-set-key (kbd "C-' C-s") 'ag-project)
(global-set-key (kbd "C-' C-n") (kbd "C-c s"))
(global-set-key (kbd "C-' C-l") 'goto-line)
(global-set-key (kbd "C-' C-d") 'dash-at-point)
(global-set-key (kbd "C-u")     'undo)
(global-set-key (kbd "C-S-u")   'redo)
(global-set-key (kbd "C-' C-i") 'change-inner)
(global-set-key (kbd "C-' C-o") 'change-outer)
(provide 'key-bindings)
