(global-set-key (kbd "C-' C-b") 'ibuffer)
(global-set-key (kbd "C-' C-f") 'find-file)
(global-set-key (kbd "C-' C-g") 'magit-status)
(global-set-key (kbd "C-' C-a") 'ack-and-a-half)
(global-set-key (kbd "C-' C-t") (kbd "M-<"))
(global-set-key (kbd "C-' C-b") (kbd "M->"))
(provide 'key-bindings)
